import '@/features/popup/popup'
import '@/features/scroll'
import '@/layout/header/header'
import '@/layout/footer/footer'

import '@/components/main-hero/main-hero'
import '@/components/about-block/about-block'
import '@/components/map/map'
import '@/components/video-block/video-block'
import '@/components/cases/cases'
